name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run lint
        run: yarn run lint

  typecheck:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
          check-latest: true
          cache: yarn
      - name: Install dependencies
        run: yarn install --frozen-lockfile
      - name: Run type check
        run: yarn run typecheck

  build-push-docker:
    needs: [lint, typecheck]
    runs-on: ubuntu-20.04
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/master'
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build (and Push)
        uses: docker/build-push-action@v2
        with:
          tags: ghcr.io/ciffelia/twauth:latest
          platforms: linux/amd64,linux/arm64/v8,linux/arm/v7,linux/arm/v6,linux/ppc64le,linux/s390x
          cache-from: type=registry,ref=ghcr.io/ciffelia/twauth:latest
          cache-to: type=inline
          push: ${{ github.ref == 'refs/heads/master' }}
